# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Pending'),
        ),
    ]
