# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=1024, verbose_name='Other Details')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Document Name')),
                ('details', models.CharField(max_length=1024, verbose_name='Location Details')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Location Name')),
                ('details', models.CharField(max_length=1024, verbose_name='Location Details')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Location Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cost')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=1024, verbose_name='Other Details')),
                ('document_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Document')),
                ('from_location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='logistics.Location')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Customer')),
                ('to_location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='logistics.Location')),
            ],
        ),
        migrations.AddField(
            model_name='productinshipment',
            name='shipment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.Shipment'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.LocationType'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.DocumentType'),
        ),
    ]
