# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_logistics', models.BooleanField(default=True)),
                ('enable_point_of_sale', models.BooleanField(default=True)),
                ('enable_retail', models.BooleanField(default=True)),
                ('enable_notes', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
