# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='website_title',
            field=models.CharField(default=datetime.datetime(2016, 5, 15, 13, 59, 4, 435759, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
