# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20160515_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Payment Amount')),
                ('other_details', models.CharField(max_length=1024, verbose_name='Other Details')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Payment Method Name')),
                ('description', models.CharField(max_length=128, verbose_name='Payment Desciption')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Outlet Name')),
                ('details', models.CharField(max_length=1024, verbose_name='Sales Outlet Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('wholesale_price', models.CharField(max_length=128, verbose_name='Wholesale Price')),
                ('retail_price', models.CharField(max_length=128, verbose_name='Retail Price')),
                ('other_details', models.CharField(max_length=1024, verbose_name='Other Details')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='productintransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Transaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Transaction'),
        ),
    ]
